name: bling
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.0.3
  build_runner: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed: ^2.2.0
  http: ^0.13.5
  intl: ^0.17.0
  json_serializable: ^6.5.4
  get_it: ^7.2.0
   
dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
